#!/usr/bin/env bash
# verify.sh — opt-in developer harness: generate sample PDFs and validate with veraPDF.
#
# This script is NOT wired into CI. Run it manually:
#
#   cd tools/pdfa3
#   bash verify.sh [--out-dir /tmp/pdfa3-verify]
#
# Requirements:
#   - Go 1.23+ on PATH (to build the sample generator)
#   - Java 11, 17, or 21 on PATH (veraPDF requires JVM)
#   - curl and tar (Linux/macOS; on Windows use WSL or Git Bash)
#
# veraPDF license: dual MPLv2 / GPLv3+. Downloaded as an external CLI tool;
# no source is vendored in this repository.
# See: https://github.com/veraPDF/veraPDF-apps

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
VERAPDF_VERSION="1.26.1"
OUT_DIR="${1:-/tmp/pdfa3-verify}"
VERAPDF_DIR="${OUT_DIR}/verapdf-bin"
REPORT_DIR="${OUT_DIR}/reports"

echo "=== PDF/A-3b verification harness (opt-in, developer-only) ==="
echo "veraPDF version : ${VERAPDF_VERSION}"
echo "output dir      : ${OUT_DIR}"
echo

mkdir -p "${OUT_DIR}" "${VERAPDF_DIR}" "${REPORT_DIR}"

# ── 1. build sample generator ─────────────────────────────────────────────
echo "[1/4] building sample generator..."
(cd "${SCRIPT_DIR}" && go build -o "${OUT_DIR}/sample" ./cmd/sample)
echo "      ok: ${OUT_DIR}/sample"

# ── 2. generate sample PDFs ────────────────────────────────────────────
echo "[2/4] generating sample PDFs..."
"${OUT_DIR}/sample" -out-dir "${OUT_DIR}"
echo "      ok: ${OUT_DIR}/sample-zatca.pdf"
echo "      ok: ${OUT_DIR}/sample-facturx.pdf"

# ── 3. download veraPDF (greenfield, MPLv2/GPLv3+) ────────────────────────────
VERAPDF_BIN="${VERAPDF_DIR}/verapdf-greenfield-${VERAPDF_VERSION}/verapdf"
if [ ! -x "${VERAPDF_BIN}" ]; then
  echo "[3/4] downloading veraPDF ${VERAPDF_VERSION} (greenfield)..."
  TARBALL="${VERAPDF_DIR}/verapdf-greenfield-${VERAPDF_VERSION}-linux.tar.gz"
  DOWNLOAD_URL="https://github.com/veraPDF/veraPDF-apps/releases/download/v${VERAPDF_VERSION}/verapdf-greenfield-${VERAPDF_VERSION}-linux.tar.gz"
  curl -fSL --output "${TARBALL}" "${DOWNLOAD_URL}"
  tar -xzf "${TARBALL}" -C "${VERAPDF_DIR}"
  chmod +x "${VERAPDF_BIN}"
  echo "      ok: ${VERAPDF_BIN}"
else
  echo "[3/4] veraPDF already present at ${VERAPDF_BIN}"
fi

# ── 4. validate each PDF ───────────────────────────────────────────────────
echo "[4/4] running veraPDF --flavour 3b ..."
echo

PASS=0
FAIL=0

validate() {
  local label="$1"
  local pdf="$2"
  local report="${REPORT_DIR}/${label}.json"

  echo "  -- ${label} --"
  set +e
  "${VERAPDF_BIN}" --flavour 3b --format json "${pdf}" > "${report}" 2>&1
  VERAPDF_EXIT=$?
  set -e

  if [ "${VERAPDF_EXIT}" -eq 0 ]; then
    echo "  PASS (exit 0) — ${pdf}"
    PASS=$((PASS + 1))
  else
    echo "  FAIL (exit ${VERAPDF_EXIT}) — ${pdf}"
    echo "  report: ${report}"
    FAIL=$((FAIL + 1))

    # Print a concise summary of failed rules
    if command -v python3 &>/dev/null; then
      python3 - "${report}" << 'PYEOF'
import json, sys
try:
    with open(sys.argv[1]) as f:
        data = json.load(f)
    results = data.get("report", {}).get("jobs", [{}])[0].get("validationResult", {})
    details = results.get("details", {})
    ruleSummaries = details.get("ruleSummaries", [])
    failed = [r for r in ruleSummaries if r.get("status") == "failed"]
    if failed:
        print(f"  failed rules ({len(failed)}):")
        for r in failed[:20]:
            clause = r.get("clause", "?")
            test = r.get("testNumber", "?")
            desc = r.get("description", "")[:80]
            count = r.get("failedChecks", "?")
            print(f"    [{clause}:{test}] ({count} checks) {desc}")
        if len(failed) > 20:
            print(f"    ... and {len(failed)-20} more (see {sys.argv[1]})")
except Exception as e:
    print(f"  (could not parse JSON report: {e})")
PYEOF
    fi
  fi
  echo
}

validate "sample-zatca"   "${OUT_DIR}/sample-zatca.pdf"
validate "sample-facturx" "${OUT_DIR}/sample-facturx.pdf"

# ── summary ─────────────────────────────────────────────────────────────────
echo "=== summary ==="
echo "  pass: ${PASS}  fail: ${FAIL}"
echo "  full reports: ${REPORT_DIR}/"
echo

if [ "${FAIL}" -gt 0 ]; then
  echo "NOTE: failures are expected for hand-built PDFs (see PDFA3_VERIFY_PLAN.md §4)."
  echo "      Known gaps documented in notes at bottom of verify.sh."
  exit 1
fi
exit 0

# ── known conformance gaps (reference only) ────────────────────────────────────────
#
# The PDFs generated by tools/pdfa3 are EXPERIMENTAL structural approximations.
# The following veraPDF rule failures are expected until remediated:
#
# 1. Embedded fonts (6.2.11.x)
#    No fonts are embedded — the blank page uses no text operators, but any
#    real content would fail this rule. The file spec uses PDF string literals,
#    not rendered text, so font checks pass structurally. LOW risk for blank page.
#
# 2. ICC colour profile (6.2.2.x / 6.2.3.x)
#    The sRGB ICC stub in minimalSRGBICC() is 128 bytes (header only, 0 tags).
#    A conformant sRGB profile requires a full tag table (wtpt, rXYZ, gXYZ,
#    bXYZ, rTRC, gTRC, bTRC, desc — minimum ~3 KB). veraPDF validates the
#    profile binary; the stub will FAIL rule 6.2.2 / AO.2 (DestOutputProfile
#    must be a valid ICC profile). MEDIUM severity.
#
# 3. /Filespec capitalisation (6.7.x)
#    The FileSpec dictionary uses /Type /Filespec (lowercase 's') whereas the
#    PDF spec requires /Type /Filespec exactly — this is correct per ISO 32000-1
#    Table 44. Verify veraPDF does not reject this.
#
# 4. XMP packet padding
#    veraPDF rule 6.1.12.1 / XMP.1 requires XMP metadata to be byte-aligned
#    with 100-byte-minimum padding after the closing xpacket. Our XMP has no
#    trailing whitespace padding. LOW-MEDIUM risk.
#
# 5. Metadata stream /Filter
#    ISO 19005-3:6.1.11.1 forbids /Filter on the XMP metadata stream object.
#    We do not apply a filter, so this should pass.
#
# 6. /AF not in PDF/A-3 profile
#    PDF/A-3 (ISO 19005-3) introduces /AF (Associated Files) as a new key.
#    veraPDF 1.26+ includes the PDF/A-3 profile; earlier versions may flag /AF
#    as an unknown key. Use veraPDF 1.26+ to validate PDF/A-3b documents.
#
# Remediation priority: ICC profile > XMP padding > font embedding (if text added)
